name: srm_hope
description: "A one-stop solution for all SRM IST needs."
publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  path_provider: ^2.1.5
  fl_chart: ^0.69.2
  url_launcher: ^6.3.1
  animations: ^2.0.11
  intl: any
  shared_preferences: ^2.3.5
  syncfusion_flutter_gauges: ^20.4.48
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
